name: masm
description: Transformer to compile .asm files via MASM32.
version: 1.0.0-dev+1
author: Tobe O <thosakwe@gmail.com>
dependencies:
  barback: ">= 0.15.2 <1.0.0"
  merge_map: ">=1.0.0 <2.0.0"
  path: ">=1.3.9 <2.0.0"
dev_dependencies:
  test: ">=0.12.14 <1.0.0"
homepage: https://github.com/thosakwe/dart_masm